/**
 * 大学（college）学术词 100
 * 格式：term|phonetic|pos|meaningCn|example|exampleCn
 */
export default [
  'abstract|ˈæbstrækt|adj./n.|抽象的；摘要|Write a 150-word abstract for the paper.|为论文写一份 150 词的摘要。',
  'academic|ˌækəˈdemɪk|adj.|学术的|Academic writing avoids casual language.|学术写作避免口语化表达。',
  'accelerate|əkˈseləreɪt|v.|加速|Online tools accelerated the research.|在线工具加快了研究进程。',
  'accommodate|əˈkɒmədeɪt|v.|容纳；顺应|The hall can accommodate 300 students.|礼堂可容纳三百名学生。',
  'accumulate|əˈkjuːmjəleɪt|v.|积累|Evidence accumulated over ten years.|证据在十年间不断积累。',
  'acknowledge|əkˈnɒlɪdʒ|v.|承认；致谢|The author acknowledges two limitations.|作者承认存在两点局限。',
  'adjacent|əˈdʒeɪsnt|adj.|邻近的|The lab is adjacent to the library.|实验室紧邻图书馆。',
  'advocate|ˈædvəkeɪt|v./n.|提倡；倡导者|Many economists advocate free trade.|许多经济学家提倡自由贸易。',
  'aesthetic|iːsˈθetɪk|adj.|美学的|The design has clear aesthetic value.|这个设计有明显的美学价值。',
  'aggregate|ˈæɡrɪɡət|n./v.|总计；合计|The aggregate score decides the ranking.|总分决定排名。',
  'allocate|ˈæləkeɪt|v.|分配|The fund allocates money to small projects.|该基金把资金分配给小项目。',
  'ambiguous|æmˈbɪɡjuəs|adj.|模棱两可的|The wording of the rule is ambiguous.|这条规则的措辞模棱两可。',
  'analogy|əˈnælədʒi|n.|类比|He explained the theory by analogy.|他用类比解释了这一理论。',
  'anticipate|ænˈtɪsɪpeɪt|v.|预期|We anticipate a rise in applications.|我们预计申请量会上升。',
  'arbitrary|ˈɑːbɪtrəri|adj.|任意的，武断的|The deadline seems entirely arbitrary.|这个截止日期显得完全武断。',
  'articulate|ɑːˈtɪkjuleɪt|v.|清晰表达|She articulated her position clearly.|她清楚地表达了立场。',
  'assess|əˈses|v.|评估|Teachers assess progress every term.|教师每学期评估进步情况。',
  'assign|əˈsaɪn|v.|分配，指派|Each group was assigned one topic.|每组分到一个题目。',
  'assumption|əˈsʌmpʃn|n.|假设|The model rests on three assumptions.|该模型建立在三个假设之上。',
  'autonomy|ɔːˈtɒnəmi|n.|自主权|Learners need some autonomy to grow.|学习者需要一定自主权才能成长。',
  'bias|ˈbaɪəs|n.|偏见|Sampling bias weakens the conclusion.|抽样偏差削弱了结论。',
  'coherent|kəʊˈhɪərənt|adj.|连贯的|A coherent essay guides the reader.|连贯的文章能引导读者。',
  'coincide|ˌkəʊɪnˈsaɪd|v.|同时发生；一致|Their findings coincide with ours.|他们的发现与我们的一致。',
  'collapse|kəˈlæps|v./n.|倒塌；崩溃|The old system collapsed under pressure.|旧体系在压力下崩溃。',
  'commodity|kəˈmɒdəti|n.|商品|Clean water is a precious commodity.|清洁水是珍贵的商品。',
  'compatible|kəmˈpætəbl|adj.|兼容的|The file is compatible with older software.|该文件与旧软件兼容。',
  'compensate|ˈkɒmpenseɪt|v.|补偿|Extra reading compensates for lost lessons.|额外阅读弥补了错过的课程。',
  'compile|kəmˈpaɪl|v.|汇编，编制|They compiled a list of local species.|他们编制了本地物种名录。',
  'comprehensive|ˌkɒmprɪˈhensɪv|adj.|全面的|The review is comprehensive and fair.|这份综述全面而公正。',
  'comprise|kəmˈpraɪz|v.|包含，构成|The course comprises six modules.|这门课程由六个模块构成。',
  'conceive|kənˈsiːv|v.|构想|It is hard to conceive of such a scale.|很难想象这样的规模。',
  'concurrent|kənˈkʌrənt|adj.|同时发生的|Two concurrent trials were carried out.|两项试验同时进行。',
  'confine|kənˈfaɪn|v.|限制|We confine the discussion to one case.|我们把讨论限定在一个案例上。',
  'conform|kənˈfɔːm|v.|遵守，符合|The building conforms to safety rules.|该建筑符合安全规定。',
  'consensus|kənˈsensəs|n.|共识|There is growing consensus on this point.|在这一点上共识日益增多。',
  'considerable|kənˈsɪdərəbl|adj.|相当大的|The change required considerable effort.|这一改变需要相当大的努力。',
  'constitute|ˈkɒnstɪtjuːt|v.|构成|Women constitute half the workforce.|女性占劳动力的一半。',
  'contradict|ˌkɒntrəˈdɪkt|v.|反驳，矛盾|These figures contradict the earlier claim.|这些数字与先前的说法矛盾。',
  'controversy|ˈkɒntrəvɜːsi|n.|争议|The policy caused public controversy.|该政策引发了公众争议。',
  'correlate|ˈkɒrəleɪt|v.|相关|Sleep correlates strongly with memory.|睡眠与记忆高度相关。',
  'criterion|kraɪˈtɪəriən|n.|标准|Clarity is the first criterion.|清晰度是首要标准。',
  'cumulative|ˈkjuːmjələtɪv|adj.|累积的|The cumulative effect is remarkable.|累积效应相当显著。',
  'deduce|dɪˈdjuːs|v.|推断|We can deduce the cause from the data.|我们可以从数据推断原因。',
  'deficit|ˈdefɪsɪt|n.|赤字，不足|The city faces a housing deficit.|该市面临住房短缺。',
  'denote|dɪˈnəʊt|v.|表示|The symbol denotes an average value.|这个符号表示平均值。',
  'derive|dɪˈraɪv|v.|源于；得出|Many English words derive from Latin.|许多英语词源于拉丁语。',
  'deviate|ˈdiːvieɪt|v.|偏离|The result deviates from the prediction.|结果偏离了预测。',
  'differentiate|ˌdɪfəˈrenʃieɪt|v.|区分|Readers must differentiate fact from opinion.|读者必须区分事实与观点。',
  'discrete|dɪˈskriːt|adj.|离散的，独立的|The task has four discrete stages.|这项任务有四个独立阶段。',
  'displace|dɪsˈpleɪs|v.|取代；迫使迁移|Automation displaced many routine jobs.|自动化取代了许多常规岗位。',
  'dispose|dɪˈspəʊz|v.|处理，处置|Dispose of batteries at the collection point.|请在回收点处理废电池。',
  'distort|dɪˈstɔːt|v.|扭曲|Small samples distort the picture.|小样本会扭曲整体图景。',
  'diversify|daɪˈvɜːsɪfaɪ|v.|多样化|The region diversified its economy.|该地区实现了经济多元化。',
  'elaborate|ɪˈlæbərət|adj./v.|详尽的；详述|Could you elaborate on that point?|你能详述那一点吗？',
  'embody|ɪmˈbɒdi|v.|体现|The design embodies a simple idea.|这个设计体现了一个简单的理念。',
  'emerge|ɪˈmɜːdʒ|v.|出现|A clear pattern emerged from the survey.|调查中出现了一个清晰的模式。',
  'empirical|ɪmˈpɪrɪkl|adj.|实证的|Empirical evidence supports the theory.|实证证据支持该理论。',
  'encompass|ɪnˈkʌmpəs|v.|涵盖|The term encompasses several meanings.|这个术语涵盖多重含义。',
  'endorse|ɪnˈdɔːs|v.|赞同，认可|Three experts endorsed the proposal.|三位专家认可了该提案。',
  'enhance|ɪnˈhɑːns|v.|提升|Visual aids enhance understanding.|视觉辅助能提升理解。',
  'entity|ˈentəti|n.|实体|A university is a legal entity.|大学是一个法律实体。',
  'equivalent|ɪˈkwɪvələnt|adj./n.|等同的；等价物|One credit is equivalent to 16 hours.|一学分相当于十六课时。',
  'erode|ɪˈrəʊd|v.|侵蚀|Rain slowly eroded the hillside.|雨水慢慢侵蚀了山坡。',
  'escalate|ˈeskəleɪt|v.|升级，加剧|Minor disputes can escalate quickly.|小争执可能迅速升级。',
  'ethical|ˈeθɪkl|adj.|伦理的|Researchers face difficult ethical choices.|研究者面临艰难的伦理抉择。',
  'evaluate|ɪˈvæljueɪt|v.|评价|Evaluate both sides before you decide.|决定前先评估双方观点。',
  'evident|ˈevɪdənt|adj.|明显的|Her talent was evident from the start.|她的才华从一开始就很明显。',
  'exceed|ɪkˈsiːd|v.|超过|Costs must not exceed the budget.|费用不得超过预算。',
  'exclude|ɪkˈskluːd|v.|排除|The study excluded incomplete records.|该研究排除了不完整记录。',
  'exhibit|ɪɡˈzɪbɪt|v.|展示；表现出|Some materials exhibit unusual strength.|某些材料表现出异常强度。',
  'explicit|ɪkˈsplɪsɪt|adj.|明确的|Give explicit instructions to avoid confusion.|给出明确说明以免混淆。',
  'exploit|ɪkˈsplɔɪt|v.|利用；剥削|We should exploit renewable resources wisely.|我们应明智地利用可再生资源。',
  'facilitate|fəˈsɪlɪteɪt|v.|促进|Good software facilitates collaboration.|好的软件促进协作。',
  'fluctuate|ˈflʌktʃueɪt|v.|波动|Prices fluctuate with the season.|价格随季节波动。',
  'formulate|ˈfɔːmjuleɪt|v.|制定，构想|They formulated a clear hypothesis.|他们提出了明确的假设。',
  'framework|ˈfreɪmwɜːk|n.|框架|The paper offers a useful framework.|这篇论文提供了有用的框架。',
  'fundamental|ˌfʌndəˈmentl|adj.|根本的|Curiosity is fundamental to science.|好奇心是科学的根本。',
  'generate|ˈdʒenəreɪt|v.|产生|The project generated valuable data.|该项目产生了宝贵数据。',
  'hierarchy|ˈhaɪərɑːki|n.|层级|The chart shows a clear hierarchy.|图表显示出清晰的层级。',
  'hypothesis|haɪˈpɒθəsɪs|n.|假设|The hypothesis was tested twice.|该假设被检验了两次。',
  'identical|aɪˈdentɪkl|adj.|完全相同的|The two samples are almost identical.|两个样本几乎完全相同。',
  'ideology|ˌaɪdiˈɒlədʒi|n.|意识形态|Ideology shapes how we read history.|意识形态影响我们如何解读历史。',
  'implement|ˈɪmplɪment|v.|实施|The school implemented the plan in March.|学校在三月实施了该计划。',
  'implicit|ɪmˈplɪsɪt|adj.|含蓄的，隐含的|The warning was implicit, not stated.|那个警告是隐含的，并未明说。',
  'incentive|ɪnˈsentɪv|n.|激励|Prizes act as a strong incentive.|奖品起到很强的激励作用。',
  'incorporate|ɪnˈkɔːpəreɪt|v.|纳入|We incorporated student feedback.|我们纳入了学生反馈。',
  'indicate|ˈɪndɪkeɪt|v.|表明|Results indicate a downward trend.|结果表明呈下降趋势。',
  'infer|ɪnˈfɜː|v.|推断|Readers can infer the author attitude.|读者可以推断作者的态度。',
  'infrastructure|ˈɪnfrəstrʌktʃə|n.|基础设施|Reliable infrastructure supports growth.|可靠的基础设施支撑增长。',
  'inherent|ɪnˈhɪərənt|adj.|固有的|Risk is inherent in any experiment.|任何实验都有固有风险。',
  'initiate|ɪˈnɪʃieɪt|v.|发起|The department initiated a pilot study.|该系发起了一项试点研究。',
  'innovate|ˈɪnəveɪt|v.|创新|Small teams often innovate faster.|小团队往往创新更快。',
  'insight|ˈɪnsaɪt|n.|洞见|The interview gave us real insight.|这次访谈给了我们真正的洞见。',
  'integrate|ˈɪntɪɡreɪt|v.|整合|We integrated the two data sets.|我们整合了两组数据。',
  'intervene|ˌɪntəˈviːn|v.|干预|Teachers rarely intervene in group work.|教师很少干预小组活动。',
  'intrinsic|ɪnˈtrɪnzɪk|adj.|内在的|Intrinsic motivation lasts longer.|内在动机持续更久。',
  'justify|ˈdʒʌstɪfaɪ|v.|证明…正当|You must justify every claim.|你必须为每个论断提供理由。',
  'characteristics|ˌkærəktəˈrɪstɪks|n.|特征|List three characteristics of the sample.|列出样本的三个特征。',
  'representative|ˌreprɪˈzentətɪv|adj./n.|有代表性的；代表|The sample is not representative.|这个样本没有代表性。',
  'differentiation|ˌdɪfərenʃiˈeɪʃn|n.|区分，差异化|Clear differentiation between the two groups is essential.|清晰区分两组样本至关重要。',
];
