/**
 * 雅思 5.5（ielts55）高频话题词 100
 * 格式：term|phonetic|pos|meaningCn|example|exampleCn
 */
export default [
  'accommodation|əˌkɒməˈdeɪʃn|n.|住宿|Student accommodation is close to campus.|学生宿舍离校园很近。',
  'advertisement|ədˈvɜːtɪsmənt|n.|广告|The advertisement misled many buyers.|这则广告误导了许多买家。',
  'agriculture|ˈæɡrɪkʌltʃə|n.|农业|Agriculture still employs many rural workers.|农业仍雇用大量农村劳动力。',
  'application|ˌæplɪˈkeɪʃn|n.|申请；应用|Submit your application before Friday.|请在周五前提交申请。',
  'appointment|əˈpɔɪntmənt|n.|预约|I made an appointment with the doctor.|我和医生预约了时间。',
  'architecture|ˈɑːkɪtektʃə|n.|建筑（学）|The city is famous for modern architecture.|这座城市以现代建筑闻名。',
  'atmosphere|ˈætməsfɪə|n.|气氛；大气|The café has a relaxing atmosphere.|这家咖啡馆气氛轻松。',
  'attraction|əˈtrækʃn|n.|吸引力；景点|The museum is the top attraction here.|博物馆是这里最热门的景点。',
  'background|ˈbækɡraʊnd|n.|背景|Students come from varied backgrounds.|学生来自不同背景。',
  'biodiversity|ˌbaɪəʊdaɪˈvɜːsəti|n.|生物多样性|Forests protect local biodiversity.|森林保护当地生物多样性。',
  'budget|ˈbʌdʒɪt|n.|预算|We planned the trip on a tight budget.|我们用紧张的预算计划了旅行。',
  'carbon|ˈkɑːbən|n.|碳|Cycling cuts your carbon footprint.|骑车能减少你的碳足迹。',
  'celebrity|səˈlebrəti|n.|名人|Celebrity culture affects young people.|名人文化影响年轻人。',
  'charity|ˈtʃærəti|n.|慈善机构|She donates to a local charity.|她向本地慈善机构捐款。',
  'childhood|ˈtʃaɪldhʊd|n.|童年|Childhood habits are hard to change.|童年养成的习惯很难改变。',
  'climate|ˈklaɪmət|n.|气候|Climate affects what farmers can grow.|气候影响农民能种什么。',
  'commuter|kəˈmjuːtə|n.|通勤者|Commuters spend hours on the road.|通勤者每天花数小时在路上。',
  'complaint|kəmˈpleɪnt|n.|投诉|The hotel received several complaints.|酒店收到了几起投诉。',
  'congestion|kənˈdʒestʃən|n.|拥堵|Congestion charges reduced city traffic.|拥堵费减少了市区交通量。',
  'consumer|kənˈsjuːmə|n.|消费者|Consumers prefer clear labelling.|消费者偏好清晰的标签。',
  'cooperation|kəʊˌɒpəˈreɪʃn|n.|合作|International cooperation is essential.|国际合作至关重要。',
  'countryside|ˈkʌntrisaɪd|n.|乡村|Many families moved to the countryside.|许多家庭搬到了乡下。',
  'creativity|ˌkriːeɪˈtɪvəti|n.|创造力|Art lessons develop creativity.|美术课培养创造力。',
  'curriculum|kəˈrɪkjələm|n.|课程体系|The curriculum includes two languages.|课程体系包含两门语言。',
  'customer|ˈkʌstəmə|n.|顾客|Good service keeps customers loyal.|优质服务留住顾客。',
  'deadline|ˈdedlaɪn|n.|截止日期|The deadline was extended by a week.|截止日期延长了一周。',
  'delivery|dɪˈlɪvəri|n.|配送|Free delivery applies to large orders.|大额订单免运费。',
  'department|dɪˈpɑːtmənt|n.|部门，系|The history department moved building.|历史系搬了楼。',
  'destination|ˌdestɪˈneɪʃn|n.|目的地|Iceland is a popular destination.|冰岛是热门旅游目的地。',
  'discount|ˈdɪskaʊnt|n.|折扣|Students get a ten percent discount.|学生享受九折优惠。',
  'distribution|ˌdɪstrɪˈbjuːʃn|n.|分布；分配|The map shows population distribution.|这张地图显示人口分布。',
  'ecosystem|ˈiːkəʊsɪstəm|n.|生态系统|A wetland is a fragile ecosystem.|湿地是脆弱的生态系统。',
  'education|ˌedʒuˈkeɪʃn|n.|教育|Free education benefits the whole society.|免费教育惠及全社会。',
  'efficiency|ɪˈfɪʃnsi|n.|效率|Energy efficiency lowers monthly bills.|能源效率降低月度账单。',
  'election|ɪˈlekʃn|n.|选举|The election takes place every four years.|选举每四年举行一次。',
  'electricity|ɪˌlekˈtrɪsəti|n.|电力|Wind now supplies much of our electricity.|风能如今提供我们大量电力。',
  'emergency|iˈmɜːdʒənsi|n.|紧急情况|Call this number in an emergency.|紧急情况请拨打此号码。',
  'emission|iˈmɪʃn|n.|排放|Vehicle emissions harm air quality.|车辆排放损害空气质量。',
  'employment|ɪmˈplɔɪmənt|n.|就业|Employment rose slightly last year.|去年就业略有上升。',
  'entertainment|ˌentəˈteɪnmənt|n.|娱乐|Streaming changed home entertainment.|流媒体改变了家庭娱乐。',
  'entrepreneur|ˌɒntrəprəˈnɜː|n.|创业者|A young entrepreneur opened the shop.|一位年轻创业者开了这家店。',
  'equipment|ɪˈkwɪpmənt|n.|设备|The gym bought new equipment.|健身房购置了新设备。',
  'expenditure|ɪkˈspendɪtʃə|n.|支出|Household expenditure rose by five percent.|家庭支出上涨了百分之五。',
  'facility|fəˈsɪləti|n.|设施|The sports facility opens at six.|体育设施六点开放。',
  'fashion|ˈfæʃn|n.|时尚|Fast fashion creates huge waste.|快时尚制造大量废弃物。',
  'fertiliser|ˈfɜːtəlaɪzə|n.|肥料|Too much fertiliser pollutes rivers.|过量肥料污染河流。',
  'fitness|ˈfɪtnəs|n.|健康，健身|Regular walking improves fitness.|经常散步能改善体能。',
  'freelance|ˈfriːlɑːns|adj.|自由职业的|Freelance work offers flexible hours.|自由职业提供灵活的工作时间。',
  'furniture|ˈfɜːnɪtʃə|n.|家具|Second-hand furniture is much cheaper.|二手家具便宜得多。',
  'government|ˈɡʌvənmənt|n.|政府|The government funded the new line.|政府资助了这条新线路。',
  'graduate|ˈɡrædʒuət|n./v.|毕业生；毕业|Graduates face a competitive market.|毕业生面对竞争激烈的市场。',
  'habitat|ˈhæbɪtæt|n.|栖息地|Building roads destroys animal habitat.|修路破坏动物栖息地。',
  'heritage|ˈherɪtɪdʒ|n.|遗产|The old town is a heritage site.|老城区是文化遗产地。',
  'hospitality|ˌhɒspɪˈtæləti|n.|款待；酒店业|She works in the hospitality industry.|她在酒店业工作。',
  'household|ˈhaʊshəʊld|n.|家庭|The average household has three members.|平均每户三口人。',
  'immigration|ˌɪmɪˈɡreɪʃn|n.|移民|Immigration policy is often debated.|移民政策常被讨论。',
  'income|ˈɪnkʌm|n.|收入|Their income doubled in five years.|他们的收入五年翻了一番。',
  'industry|ˈɪndəstri|n.|工业，行业|The film industry employs thousands.|电影业雇用了成千上万人。',
  'inequality|ˌɪnɪˈkwɒləti|n.|不平等|Income inequality remains a problem.|收入不平等仍是问题。',
  'ingredient|ɪnˈɡriːdiənt|n.|原料，要素|Read the ingredients on the label.|阅读标签上的成分表。',
  'insurance|ɪnˈʃʊərəns|n.|保险|Travel insurance covers lost luggage.|旅游保险涵盖行李丢失。',
  'interview|ˈɪntəvjuː|n./v.|面试；采访|The interview lasted forty minutes.|面试持续了四十分钟。',
  'investment|ɪnˈvestmənt|n.|投资|Education is a long-term investment.|教育是长期投资。',
  'journalist|ˈdʒɜːnəlɪst|n.|记者|The journalist checked every source.|这位记者核实了每个信源。',
  'landscape|ˈlændskeɪp|n.|风景，地貌|The landscape changes with altitude.|地貌随海拔变化。',
  'leisure|ˈleʒə|n.|闲暇|People have less leisure time now.|人们现在闲暇时间更少。',
  'lifestyle|ˈlaɪfstaɪl|n.|生活方式|A sedentary lifestyle harms health.|久坐的生活方式损害健康。',
  'literacy|ˈlɪtərəsi|n.|识字，素养|Digital literacy is now essential.|数字素养如今必不可少。',
  'luggage|ˈlʌɡɪdʒ|n.|行李|Keep your luggage with you.|请随身看管行李。',
  'maintenance|ˈmeɪntənəns|n.|维护|Regular maintenance prevents breakdowns.|定期维护可防止故障。',
  'manufacture|ˌmænjuˈfæktʃə|v./n.|制造|The plant manufactures solar panels.|这家工厂制造太阳能板。',
  'marketing|ˈmɑːkɪtɪŋ|n.|营销|Social media changed marketing forever.|社交媒体永久改变了营销。',
  'membership|ˈmembəʃɪp|n.|会员资格|Annual membership costs sixty pounds.|年度会员费六十英镑。',
  'monument|ˈmɒnjumənt|n.|纪念碑|The monument dates from 1890.|这座纪念碑建于 1890 年。',
  'neighbourhood|ˈneɪbəhʊd|n.|社区，街区|It is a quiet neighbourhood.|这是个安静的街区。',
  'nutrition|njuˈtrɪʃn|n.|营养|Good nutrition supports concentration.|良好营养有助于集中注意力。',
  'obesity|əʊˈbiːsəti|n.|肥胖|Childhood obesity is rising fast.|儿童肥胖率上升很快。',
  'opportunity|ˌɒpəˈtjuːnəti|n.|机会|Volunteering creates new opportunities.|做志愿者创造新机会。',
  'packaging|ˈpækɪdʒɪŋ|n.|包装|Plastic packaging is hard to recycle.|塑料包装难以回收。',
  'passenger|ˈpæsɪndʒə|n.|乘客|Passengers must keep tickets safe.|乘客须妥善保管车票。',
  'pedestrian|pəˈdestriən|n.|行人|The street is closed to pedestrians.|这条街对行人封闭。',
  'pesticide|ˈpestɪsaɪd|n.|杀虫剂|Pesticide use worries many consumers.|杀虫剂的使用让许多消费者担忧。',
  'pollution|pəˈluːʃn|n.|污染|Air pollution fell during the lockdown.|封控期间空气污染下降。',
  'population|ˌpɒpjuˈleɪʃn|n.|人口|The population is ageing steadily.|人口正稳步老龄化。',
  'poverty|ˈpɒvəti|n.|贫困|Education helps people escape poverty.|教育帮助人们摆脱贫困。',
  'priority|praɪˈɒrəti|n.|优先事项|Safety is our first priority.|安全是我们的首要任务。',
  'productivity|ˌprɒdʌkˈtɪvəti|n.|生产力|Short breaks raise productivity.|短暂休息能提高生产力。',
  'profession|prəˈfeʃn|n.|职业|Teaching is a respected profession.|教师是受尊敬的职业。',
  'qualification|ˌkwɒlɪfɪˈkeɪʃn|n.|资格，学历|The job needs a formal qualification.|这份工作需要正式资历。',
  'questionnaire|ˌkwestʃəˈneə|n.|问卷|Two hundred people returned the questionnaire.|两百人交回了问卷。',
  'recycling|ˌriːˈsaɪklɪŋ|n.|回收利用|Recycling rates vary between cities.|各城市回收率不同。',
  'renewable|rɪˈnjuːəbl|adj.|可再生的|Renewable energy is getting cheaper.|可再生能源正变得更便宜。',
  'reputation|ˌrepjuˈteɪʃn|n.|声誉|The school has an excellent reputation.|这所学校声誉极佳。',
  'resource|rɪˈsɔːs|n.|资源|Water is a limited resource.|水是有限的资源。',
  'retirement|rɪˈtaɪəmənt|n.|退休|He took early retirement last year.|他去年提前退休了。',
  'scholarship|ˈskɒləʃɪp|n.|奖学金|She won a full scholarship.|她获得了全额奖学金。',
  'shortage|ˈʃɔːtɪdʒ|n.|短缺|There is a shortage of skilled staff.|技术人员短缺。',
  'statistics|stəˈtɪstɪks|n.|统计数据|The statistics come from a 2023 survey.|这些统计来自 2023 年的调查。',
  'sustainability|səˌsteɪnəˈbɪləti|n.|可持续性|Sustainability guides every decision.|可持续性指导每项决策。',
  'unemployment|ˌʌnɪmˈplɔɪmənt|n.|失业|Youth unemployment fell slightly.|青年失业率略有下降。',
];
