/**
 * 雅思 6.0-6.5（ielts65）论证高频词 100
 * 格式：term|phonetic|pos|meaningCn|example|exampleCn
 */
export default [
  'alleviate|əˈliːvieɪt|v.|减轻，缓解|Subsidies can alleviate rural poverty.|补贴能够缓解农村贫困。',
  'ambivalent|æmˈbɪvələnt|adj.|矛盾的|Voters remain ambivalent about the reform.|选民对这项改革仍持矛盾态度。',
  'amplify|ˈæmplɪfaɪ|v.|放大，加强|Social media amplifies extreme opinions.|社交媒体放大了极端观点。',
  'appraise|əˈpreɪz|v.|评估|Managers appraise staff twice a year.|管理者每年评估员工两次。',
  'ascertain|ˌæsəˈteɪn|v.|查明|Researchers could not ascertain the cause.|研究者未能查明原因。',
  'attribute|əˈtrɪbjuːt|v.|归因于|Experts attribute the rise to warmer winters.|专家将上升归因于更暖的冬天。',
  'augment|ɔːɡˈment|v.|增加，增强|Part-time work augments student income.|兼职增加了学生收入。',
  'authenticity|ˌɔːθenˈtɪsəti|n.|真实性|Readers question the authenticity of the report.|读者质疑该报告的真实性。',
  'beneficiary|ˌbenɪˈfɪʃəri|n.|受益者|Small farmers are the main beneficiaries.|小农户是主要受益者。',
  'bolster|ˈbəʊlstə|v.|支撑，加强|New data bolster the original claim.|新数据支持了最初的论断。',
  'catalyst|ˈkætəlɪst|n.|催化剂，促因|The crisis acted as a catalyst for change.|这场危机成为变革的催化剂。',
  'cognitive|ˈkɒɡnətɪv|adj.|认知的|Sleep loss impairs cognitive performance.|睡眠不足损害认知表现。',
  'commence|kəˈmens|v.|开始|Construction will commence in April.|施工将于四月开始。',
  'compelling|kəmˈpelɪŋ|adj.|令人信服的|She presented a compelling argument.|她提出了令人信服的论点。',
  'compliance|kəmˈplaɪəns|n.|合规，遵守|Compliance with safety rules is mandatory.|遵守安全规定是强制性的。',
  'comprehend|ˌkɒmprɪˈhend|v.|理解|Few readers fully comprehend the statistics.|很少有读者完全理解这些统计。',
  'conducive|kənˈdjuːsɪv|adj.|有助于…的|Open plan offices are not conducive to focus.|开放式办公室不利于专注。',
  'connotation|ˌkɒnəˈteɪʃn|n.|隐含意义|The word carries a negative connotation.|这个词带有负面含义。',
  'consolidate|kənˈsɒlɪdeɪt|v.|巩固；合并|Review consolidates what you have learnt.|复习巩固你已学的内容。',
  'constrain|kənˈstreɪn|v.|限制|Limited funding constrains the project.|有限的资金限制了这个项目。',
  'contingent|kənˈtɪndʒənt|adj.|视情况而定的|Payment is contingent on delivery.|付款视交付情况而定。',
  'converge|kənˈvɜːdʒ|v.|汇聚|The two theories converge on one point.|两种理论在一点上趋于一致。',
  'culminate|ˈkʌlmɪneɪt|v.|以…告终|The course culminates in a group project.|课程以小组项目收尾。',
  'curtail|kɜːˈteɪl|v.|削减|The city curtailed night bus services.|该市削减了夜间公交服务。',
  'decisive|dɪˈsaɪsɪv|adj.|决定性的|Timing proved decisive in the debate.|时机在辩论中起了决定作用。',
  'deficiency|dɪˈfɪʃnsi|n.|缺乏|Vitamin deficiency causes tiredness.|维生素缺乏导致疲劳。',
  'deliberate|dɪˈlɪbərət|adj.|故意的；深思熟虑的|The omission looks deliberate.|这一遗漏看起来是故意的。',
  'deteriorate|dɪˈtɪəriəreɪt|v.|恶化|Air quality deteriorated after the fire.|火灾后空气质量恶化。',
  'detrimental|ˌdetrɪˈmentl|adj.|有害的|Excessive screen time is detrimental to sleep.|过度使用屏幕有害睡眠。',
  'discrepancy|dɪsˈkrepənsi|n.|差异，不符|There is a discrepancy between the two records.|两份记录之间存在不符。',
  'disparity|dɪˈspærəti|n.|悬殊差异|Regional disparity remains substantial.|地区差距依然显著。',
  'disseminate|dɪˈsemɪneɪt|v.|传播|Universities disseminate research findings freely.|大学免费传播研究成果。',
  'distinctive|dɪˈstɪŋktɪv|adj.|独特的|The building has a distinctive roof.|这座建筑有独特的屋顶。',
  'divergent|daɪˈvɜːdʒənt|adj.|分歧的|Experts hold divergent views on this.|专家对此持不同看法。',
  'elicit|iˈlɪsɪt|v.|引出，激起|Open questions elicit longer answers.|开放式问题能引出更长的回答。',
  'emulate|ˈemjuleɪt|v.|效仿|Other cities hope to emulate the model.|其他城市希望效仿这一模式。',
  'endeavour|ɪnˈdevə|n./v.|努力|Despite our best endeavour, costs rose.|尽管我们尽了最大努力，成本仍上涨。',
  'entail|ɪnˈteɪl|v.|需要，涉及|The role entails frequent travel.|这个岗位需要经常出差。',
  'equitable|ˈekwɪtəbl|adj.|公平的|We need an equitable distribution of funds.|我们需要公平的资金分配。',
  'eradicate|ɪˈrædɪkeɪt|v.|根除|Vaccines helped eradicate the disease.|疫苗帮助根除了这种疾病。',
  'exacerbate|ɪɡˈzæsəbeɪt|v.|加剧|Cutting buses would exacerbate congestion.|削减公交会加剧拥堵。',
  'exemplify|ɪɡˈzemplɪfaɪ|v.|例证|This case exemplifies the wider trend.|这个案例例证了更广泛的趋势。',
  'expedite|ˈekspədaɪt|v.|加快|Online forms expedite the whole process.|在线表格加快了整个流程。',
  'exponential|ˌekspəˈnenʃl|adj.|指数级的|The app saw exponential growth.|这款应用实现了指数级增长。',
  'feasible|ˈfiːzəbl|adj.|可行的|The plan is technically feasible.|该计划在技术上可行。',
  'foster|ˈfɒstə|v.|培养，促进|Group tasks foster cooperation.|小组任务促进合作。',
  'gauge|ɡeɪdʒ|v.|判断，衡量|Surveys gauge public opinion.|调查衡量公众意见。',
  'hinder|ˈhɪndə|v.|阻碍|Poor lighting hinders night study.|照明不足妨碍夜间学习。',
  'holistic|həʊˈlɪstɪk|adj.|整体的|The school takes a holistic approach.|这所学校采取整体性的方法。',
  'illuminate|ɪˈluːmɪneɪt|v.|阐明；照亮|The example illuminates a difficult idea.|这个例子阐明了一个难懂的观点。',
  'impede|ɪmˈpiːd|v.|阻碍|Heavy rain impeded the rescue.|大雨阻碍了救援。',
  'imperative|ɪmˈperətɪv|adj.|紧要的|It is imperative to act now.|现在采取行动至关重要。',
  'impetus|ˈɪmpɪtəs|n.|推动力|The award gave fresh impetus to the team.|这个奖项给团队带来新动力。',
  'implication|ˌɪmplɪˈkeɪʃn|n.|影响，含义|Consider the implications for teaching.|考虑一下对教学的影响。',
  'inclination|ˌɪnklɪˈneɪʃn|n.|倾向|He shows little inclination to change.|他几乎没有改变的意愿。',
  'induce|ɪnˈdjuːs|v.|引起，诱导|Discounts induce impulse buying.|折扣诱发冲动购物。',
  'inevitable|ɪnˈevɪtəbl|adj.|不可避免的|Some errors are inevitable.|有些错误不可避免。',
  'influx|ˈɪnflʌks|n.|涌入|The city saw an influx of tourists.|该市迎来了游客涌入。',
  'inhibit|ɪnˈhɪbɪt|v.|抑制|Fear of failure inhibits creativity.|对失败的恐惧抑制创造力。',
  'integral|ˈɪntɪɡrəl|adj.|不可或缺的|Feedback is integral to progress.|反馈是进步不可或缺的部分。',
  'intricate|ˈɪntrɪkət|adj.|错综复杂的|The system has an intricate structure.|这个系统结构错综复杂。',
  'invaluable|ɪnˈvæljuəbl|adj.|极宝贵的|Her advice proved invaluable.|她的建议极其宝贵。',
  'jeopardise|ˈdʒepədaɪz|v.|危及|Delays could jeopardise the whole plan.|延误可能危及整个计划。',
  'legitimate|lɪˈdʒɪtɪmət|adj.|合理的，合法的|That is a legitimate concern.|那是个合理的担忧。',
  'leverage|ˈliːvərɪdʒ|v./n.|利用；杠杆|Small firms leverage online platforms.|小公司利用在线平台。',
  'magnitude|ˈmæɡnɪtjuːd|n.|规模，重要性|Few grasp the magnitude of the change.|很少有人理解这一变化的规模。',
  'mandate|ˈmændeɪt|n./v.|强制要求|The law mandates seat belts.|法律强制要求系安全带。',
  'mediate|ˈmiːdieɪt|v.|调解|A third party mediated the dispute.|第三方调解了这场争端。',
  'meticulous|məˈtɪkjələs|adj.|一丝不苟的|She keeps meticulous records.|她的记录一丝不苟。',
  'mitigate|ˈmɪtɪɡeɪt|v.|减轻|Tree planting mitigates urban heat.|种树可减轻城市热岛效应。',
  'momentum|məˈmentəm|n.|势头|The campaign gained momentum quickly.|这场运动迅速获得势头。',
  'negligible|ˈneɡlɪdʒəbl|adj.|微不足道的|The cost difference is negligible.|成本差异微不足道。',
  'notwithstanding|ˌnɒtwɪθˈstændɪŋ|prep.|尽管|Notwithstanding the delay, we finished.|尽管有延误，我们还是完成了。',
  'nurture|ˈnɜːtʃə|v.|培育|Schools should nurture curiosity.|学校应培育好奇心。',
  'obsolete|ˈɒbsəliːt|adj.|过时的|The software became obsolete in two years.|这款软件两年就过时了。',
  'offset|ˌɒfˈset|v.|抵消|Tree planting offsets some emissions.|植树抵消了部分排放。',
  'optimal|ˈɒptɪməl|adj.|最优的|Find the optimal balance of cost and quality.|找到成本与质量的最优平衡。',
  'outweigh|ˌaʊtˈweɪ|v.|重于，胜过|The benefits clearly outweigh the risks.|好处显然大于风险。',
  'paradigm|ˈpærədaɪm|n.|范式|Remote work created a new paradigm.|远程办公创造了新范式。',
  'paramount|ˈpærəmaʊnt|adj.|首要的|Safety is of paramount importance.|安全是头等重要的。',
  'perceive|pəˈsiːv|v.|感知，认为|People perceive risk differently.|人们对风险的感知不同。',
  'persistent|pəˈsɪstənt|adj.|持续的，坚持的|Persistent effort produces results.|持续的努力产生结果。',
  'pertinent|ˈpɜːtɪnənt|adj.|切题的|Please keep your comments pertinent.|请让你的评论切题。',
  'phenomenon|fəˈnɒmɪnən|n.|现象|Urban migration is a global phenomenon.|城市迁移是全球现象。',
  'plausible|ˈplɔːzəbl|adj.|貌似合理的|That is a plausible explanation.|那是个看似合理的解释。',
  'precede|prɪˈsiːd|v.|先于|A short briefing precedes each session.|每场活动前有简短说明。',
  'predominant|prɪˈdɒmɪnənt|adj.|主要的|Rice is the predominant crop here.|水稻是这里的主要作物。',
  'prevalent|ˈprevələnt|adj.|普遍的|The habit is prevalent among teenagers.|这种习惯在青少年中很普遍。',
  'proficiency|prəˈfɪʃnsi|n.|熟练程度|Language proficiency opens doors.|语言熟练程度打开机会之门。',
  'profound|prəˈfaʊnd|adj.|深刻的|The book had a profound effect on me.|这本书对我影响深远。',
  'reinforce|ˌriːɪnˈfɔːs|v.|强化|Examples reinforce abstract rules.|例子强化抽象规则。',
  'restrict|rɪˈstrɪkt|v.|限制|Some cities restrict car access.|一些城市限制汽车通行。',
  'scrutiny|ˈskruːtəni|n.|审视|The plan came under close scrutiny.|该计划受到严密审视。',
  'simultaneously|ˌsɪmlˈteɪniəsli|adv.|同时地|Two events happened simultaneously.|两件事同时发生。',
  'subsequent|ˈsʌbsɪkwənt|adj.|随后的|Subsequent studies confirmed the result.|随后的研究证实了这一结果。',
  'substantial|səbˈstænʃl|adj.|大量的|A substantial minority disagreed.|相当一部分人不同意。',
  'undermine|ˌʌndəˈmaɪn|v.|削弱|Constant criticism undermines confidence.|不断的批评削弱信心。',
  'viable|ˈvaɪəbl|adj.|可行的|Solar power is now a viable option.|太阳能如今是可行的选择。',
  'widespread|ˈwaɪdspred|adj.|广泛的|The practice is widespread in Europe.|这种做法在欧洲很普遍。',
  'counterproductive|ˌkaʊntəprəˈdʌktɪv|adj.|适得其反的|Punishing mistakes can be counterproductive.|惩罚错误可能适得其反。',
];
