/**
 * 高中（senior）核心词 100
 * 格式：term|phonetic|pos|meaningCn|example|exampleCn
 */
export default [
  'accurate|ˈækjərət|adj.|准确的|The report gives an accurate picture of the market.|这份报告准确反映了市场状况。',
  'achievement|əˈtʃiːvmənt|n.|成就|Landing on the moon was a great achievement.|登月是一项伟大成就。',
  'acquire|əˈkwaɪə|v.|获得，习得|Children acquire language surprisingly fast.|儿童习得语言的速度惊人。',
  'adapt|əˈdæpt|v.|适应；改编|Plants adapt to dry weather in clever ways.|植物以巧妙的方式适应干燥天气。',
  'adequate|ˈædɪkwət|adj.|足够的，适当的|The room is adequate for six people.|这个房间容纳六个人足够了。',
  'adjust|əˈdʒʌst|v.|调整|You may adjust the seat to a comfortable height.|你可以把座椅调到舒服的高度。',
  'admire|ədˈmaɪə|v.|钦佩，欣赏|I admire her patience with beginners.|我钦佩她对初学者的耐心。',
  'adopt|əˈdɒpt|v.|采纳；收养|The school adopted a new timetable.|学校采用了新的课程表。',
  'advantage|ədˈvɑːntɪdʒ|n.|优势|Small classes have a clear advantage.|小班教学有明显优势。',
  'affect|əˈfekt|v.|影响|Noise seriously affects concentration.|噪音严重影响注意力。',
  'afford|əˈfɔːd|v.|负担得起|Few students can afford that laptop.|很少有学生买得起那款笔记本电脑。',
  'aggressive|əˈɡresɪv|adj.|好斗的；有进取心的|His aggressive tone upset the whole group.|他咄咄逼人的语气惹恼了全组人。',
  'alternative|ɔːlˈtɜːnətɪv|n./adj.|替代方案；可替代的|Cycling is a healthy alternative to driving.|骑车是开车的健康替代方式。',
  'ambition|æmˈbɪʃn|n.|抱负，志向|Her ambition is to design bridges.|她的志向是设计桥梁。',
  'amount|əˈmaʊnt|n.|数量|A large amount of water was wasted.|大量的水被浪费了。',
  'analyse|ˈænəlaɪz|v.|分析|Let us analyse the data before deciding.|决定之前我们先分析数据。',
  'announce|əˈnaʊns|v.|宣布|The head teacher announced the results.|校长宣布了结果。',
  'annual|ˈænjuəl|adj.|每年的|The annual report comes out in May.|年度报告在五月发布。',
  'anxious|ˈæŋkʃəs|adj.|焦虑的|Many students feel anxious before exams.|许多学生考前感到焦虑。',
  'apologise|əˈpɒlədʒaɪz|v.|道歉|He apologised for arriving late.|他为迟到道歉。',
  'apparent|əˈpærənt|adj.|显然的|It soon became apparent that we were lost.|很快就明显看出我们迷路了。',
  'appreciate|əˈpriːʃieɪt|v.|感激；欣赏|I appreciate your honest feedback.|我感谢你诚实的反馈。',
  'approach|əˈprəʊtʃ|n./v.|方法；接近|We need a fresh approach to the problem.|我们需要解决问题的新方法。',
  'appropriate|əˈprəʊpriət|adj.|恰当的|Jeans are not appropriate for the ceremony.|牛仔裤不适合这个典礼。',
  'approve|əˈpruːv|v.|批准；赞成|The committee approved the budget.|委员会批准了预算。',
  'argue|ˈɑːɡjuː|v.|争论；主张|Some people argue that homework is useless.|有人主张家庭作业没有用。',
  'arrange|əˈreɪndʒ|v.|安排|I will arrange a meeting for Friday.|我会安排周五的会议。',
  'aspect|ˈæspekt|n.|方面|Cost is only one aspect of the plan.|成本只是这个计划的一个方面。',
  'assume|əˈsjuːm|v.|假定，认为|Do not assume that everyone agrees.|不要假定人人都同意。',
  'athlete|ˈæθliːt|n.|运动员|The athlete trains six days a week.|这名运动员每周训练六天。',
  'attempt|əˈtempt|n./v.|尝试|Her first attempt at cooking failed.|她第一次尝试做饭失败了。',
  'attitude|ˈætɪtjuːd|n.|态度|A positive attitude makes learning easier.|积极的态度使学习更容易。',
  'attract|əˈtrækt|v.|吸引|The festival attracts visitors from abroad.|这个节日吸引了国外游客。',
  'authority|ɔːˈθɒrəti|n.|权威；当局|The local authority repaired the road.|地方当局修好了这条路。',
  'available|əˈveɪləbl|adj.|可获得的|Free tickets are available online.|网上可以领取免费票。',
  'aware|əˈweə|adj.|意识到的|Are you aware of the new rule?|你知道那条新规定吗？',
  'barrier|ˈbæriə|n.|障碍|Shyness can be a barrier to speaking.|害羞可能成为开口说话的障碍。',
  'basis|ˈbeɪsɪs|n.|基础，依据|Trust is the basis of teamwork.|信任是团队合作的基础。',
  'behave|bɪˈheɪv|v.|表现，举止|The class behaved well during the visit.|参观期间全班表现良好。',
  'brilliant|ˈbrɪliənt|adj.|杰出的；明亮的|That was a brilliant piece of writing.|那是一篇出色的文章。',
  'calculate|ˈkælkjuleɪt|v.|计算|Calculate the total cost before you buy.|购买前先算好总花费。',
  'campaign|kæmˈpeɪn|n.|运动，活动|The campaign raised money for the library.|这项活动为图书馆筹了款。',
  'capable|ˈkeɪpəbl|adj.|有能力的|She is capable of leading the team.|她有能力带领这个团队。',
  'capacity|kəˈpæsəti|n.|容量；能力|The hall has a capacity of 500.|这个礼堂可容纳五百人。',
  'category|ˈkætəɡəri|n.|类别|Sort the books into three categories.|把书分成三类。',
  'cautious|ˈkɔːʃəs|adj.|谨慎的|Be cautious when you share personal data.|分享个人数据时要谨慎。',
  'ceremony|ˈserəməni|n.|典礼|The opening ceremony starts at nine.|开幕式九点开始。',
  'circumstance|ˈsɜːkəmstəns|n.|情况，环境|Under no circumstance should you cheat.|在任何情况下都不应作弊。',
  'citizen|ˈsɪtɪzn|n.|公民|Every citizen has the right to vote.|每个公民都有投票权。',
  'civilisation|ˌsɪvəlaɪˈzeɪʃn|n.|文明|Ancient civilisation left us many wonders.|古代文明给我们留下许多奇迹。',
  'claim|kleɪm|v./n.|声称；主张|He claims that the test was unfair.|他声称这次测试不公平。',
  'classify|ˈklæsɪfaɪ|v.|分类|Scientists classify animals by structure.|科学家按结构给动物分类。',
  'colleague|ˈkɒliːɡ|n.|同事|My colleague helped me with the report.|同事帮我完成了报告。',
  'combine|kəmˈbaɪn|v.|结合|The course combines theory and practice.|这门课把理论与实践结合起来。',
  'commercial|kəˈmɜːʃl|adj.|商业的|The film was a commercial success.|这部电影在商业上很成功。',
  'commit|kəˈmɪt|v.|承诺；犯（错）|We commit ourselves to daily practice.|我们承诺每天练习。',
  'community|kəˈmjuːnəti|n.|社区，群体|The community built a small park.|社区建了一座小公园。',
  'competition|ˌkɒmpəˈtɪʃn|n.|竞争；比赛|The writing competition is open to all.|写作比赛向所有人开放。',
  'complex|ˈkɒmpleks|adj.|复杂的|Climate change is a complex issue.|气候变化是个复杂问题。',
  'concentrate|ˈkɒnsntreɪt|v.|集中注意力|I cannot concentrate with music on.|开着音乐我无法集中注意力。',
  'conclude|kənˈkluːd|v.|得出结论；结束|We concluded that the method works.|我们得出结论：这个方法有效。',
  'confident|ˈkɒnfɪdənt|adj.|自信的|She sounded confident in the interview.|她在面试中显得很自信。',
  'confirm|kənˈfɜːm|v.|确认|Please confirm your booking by email.|请通过邮件确认预订。',
  'conflict|ˈkɒnflɪkt|n.|冲突|The two plans are in conflict.|这两个方案相互冲突。',
  'consequence|ˈkɒnsɪkwəns|n.|后果|Every choice has a consequence.|每个选择都有后果。',
  'conservation|ˌkɒnsəˈveɪʃn|n.|保护，保存|Water conservation saves money too.|节约用水也省钱。',
  'consistent|kənˈsɪstənt|adj.|一致的；持续的|Consistent practice beats talent.|持续练习胜过天赋。',
  'constant|ˈkɒnstənt|adj.|不断的|Constant noise made study impossible.|不断的噪音让学习无法进行。',
  'construct|kənˈstrʌkt|v.|建造；构造|They constructed a bridge in six months.|他们六个月建成一座桥。',
  'consume|kənˈsjuːm|v.|消耗；消费|Old bulbs consume far more energy.|旧灯泡耗电多得多。',
  'contain|kənˈteɪn|v.|包含|This drink contains no sugar.|这种饮料不含糖。',
  'contemporary|kənˈtemprəri|adj.|当代的|The gallery shows contemporary art.|这家画廊展出当代艺术。',
  'context|ˈkɒntekst|n.|语境；背景|Guess the meaning from the context.|根据上下文猜测词义。',
  'contribute|kənˈtrɪbjuːt|v.|贡献|Everyone contributed one idea.|每个人都贡献了一个想法。',
  'convince|kənˈvɪns|v.|说服|His evidence convinced the judges.|他的证据说服了评委。',
  'cooperate|kəʊˈɒpəreɪt|v.|合作|The two schools cooperate on projects.|两所学校在项目上合作。',
  'criticise|ˈkrɪtɪsaɪz|v.|批评|It is easy to criticise, harder to build.|批评容易，建设难。',
  'crucial|ˈkruːʃl|adj.|至关重要的|The first ten minutes are crucial.|开头十分钟至关重要。',
  'cultural|ˈkʌltʃərəl|adj.|文化的|Cultural differences shape daily habits.|文化差异塑造日常习惯。',
  'currency|ˈkʌrənsi|n.|货币|The local currency is quite stable.|当地货币相当稳定。',
  'decline|dɪˈklaɪn|v./n.|下降；婉拒|Bird numbers have declined sharply.|鸟类数量急剧下降。',
  'dedicate|ˈdedɪkeɪt|v.|奉献，致力于|She dedicated her life to teaching.|她把一生献给了教育。',
  'delicate|ˈdelɪkət|adj.|精细的；脆弱的|This is a delicate balance to keep.|这是个需要小心维持的平衡。',
  'deliver|dɪˈlɪvə|v.|递送；发表|He delivered a short speech.|他做了一个简短的演讲。',
  'demand|dɪˈmɑːnd|n./v.|需求；要求|Demand for the course is very high.|这门课的需求非常大。',
  'demonstrate|ˈdemənstreɪt|v.|证明；演示|The results demonstrate real progress.|结果证明有真正的进步。',
  'deny|dɪˈnaɪ|v.|否认|He denied breaking the window.|他否认打破了窗户。',
  'deserve|dɪˈzɜːv|v.|应得|Your team deserves the prize.|你们队应得这个奖。',
  'destroy|dɪˈstrɔɪ|v.|摧毁|The storm destroyed several houses.|风暴摧毁了几座房子。',
  'determine|dɪˈtɜːmɪn|v.|决定；确定|Your effort determines your progress.|你的努力决定你的进步。',
  'device|dɪˈvaɪs|n.|装置，设备|This device measures air quality.|这个装置测量空气质量。',
  'devote|dɪˈvəʊt|v.|投入，献身|He devotes two hours a day to reading.|他每天投入两小时阅读。',
  'diligent|ˈdɪlɪdʒənt|adj.|勤奋的|Diligent students revise a little daily.|勤奋的学生每天复习一点。',
  'diverse|daɪˈvɜːs|adj.|多样的|The city has a diverse population.|这座城市人口多样。',
  'domestic|dəˈmestɪk|adj.|国内的；家庭的|Domestic flights are cheaper now.|国内航班现在便宜些。',
  'efficient|ɪˈfɪʃnt|adj.|高效的|An efficient method saves hours.|高效的方法能省下几个小时。',
  'eliminate|ɪˈlɪmɪneɪt|v.|消除，淘汰|We must eliminate careless mistakes.|我们必须消除粗心的错误。',
  'emphasise|ˈemfəsaɪz|v.|强调|The teacher emphasised accuracy.|老师强调准确性。',
  'establish|ɪˈstæblɪʃ|v.|建立|The club was established in 1998.|这个俱乐部建于 1998 年。',
  'evidence|ˈevɪdəns|n.|证据|There is strong evidence for this view.|这一观点有强有力的证据。',
];
