/**
 * 初中（junior）核心词 100
 * 格式：term|phonetic|pos|meaningCn|example|exampleCn
 * 注意：phonetic 不带斜杠，生成器会自动补 /.../
 */
export default [
  'ability|əˈbɪləti|n.|能力，才能|She has the ability to solve difficult problems.|她有解决难题的能力。',
  'achieve|əˈtʃiːv|v.|实现，达到|You can achieve your dream with hard work.|努力就能实现你的梦想。',
  'active|ˈæktɪv|adj.|积极的，活跃的|He is active in every class discussion.|他在每次课堂讨论中都很积极。',
  'addition|əˈdɪʃn|n.|增加；加法|In addition, we need two more chairs.|另外，我们还需要两把椅子。',
  'advice|ədˈvaɪs|n.|建议，忠告|My teacher gave me some useful advice.|老师给了我一些有用的建议。',
  'afraid|əˈfreɪd|adj.|害怕的|Do not be afraid of making mistakes.|不要害怕犯错。',
  'agree|əˈɡriː|v.|同意，赞成|I agree with your plan.|我同意你的计划。',
  'allow|əˈlaʊ|v.|允许，准许|My parents allow me to go out on Sunday.|父母允许我周日外出。',
  'already|ɔːlˈredi|adv.|已经|The film has already started.|电影已经开始了。',
  'although|ɔːlˈðəʊ|conj.|虽然，尽管|Although it was raining, we went out.|虽然下雨，我们还是出去了。',
  'amazing|əˈmeɪzɪŋ|adj.|令人惊奇的|The view from the top is amazing.|山顶的景色令人惊叹。',
  'ancient|ˈeɪnʃənt|adj.|古代的，古老的|This is an ancient Chinese story.|这是一个中国古代故事。',
  'angry|ˈæŋɡri|adj.|生气的|My father was angry about my grades.|爸爸对我的成绩很生气。',
  'animal|ˈænɪml|n.|动物|Pandas are my favourite animal.|熊猫是我最喜欢的动物。',
  'answer|ˈɑːnsə|v./n.|回答；答案|Please answer the question in English.|请用英语回答这个问题。',
  'appear|əˈpɪə|v.|出现；显得|A rainbow appeared after the rain.|雨后出现了一道彩虹。',
  'article|ˈɑːtɪkl|n.|文章|I read an article about healthy eating.|我读了一篇关于健康饮食的文章。',
  'attention|əˈtenʃn|n.|注意，专心|Please pay attention to the blackboard.|请注意看黑板。',
  'average|ˈævərɪdʒ|adj./n.|平均的；平均数|The average score was seventy-five.|平均分是七十五分。',
  'avoid|əˈvɔɪd|v.|避免|We should avoid eating too much sugar.|我们应避免吃太多糖。',
  'balance|ˈbæləns|n./v.|平衡|It is hard to balance study and sport.|很难平衡学习与运动。',
  'beautiful|ˈbjuːtɪfl|adj.|美丽的|What a beautiful garden!|多美的花园啊！',
  'believe|bɪˈliːv|v.|相信|I believe you can do better next time.|我相信你下次能做得更好。',
  'benefit|ˈbenɪfɪt|n./v.|好处；有益于|Reading brings many benefits.|阅读带来许多好处。',
  'borrow|ˈbɒrəʊ|v.|借入|May I borrow your dictionary?|我可以借用你的字典吗？',
  'breathe|briːð|v.|呼吸|Trees help us breathe clean air.|树木帮助我们呼吸清洁的空气。',
  'bright|braɪt|adj.|明亮的；聪明的|The classroom is bright and tidy.|教室明亮整洁。',
  'careful|ˈkeəfl|adj.|小心的|Be careful when you cross the road.|过马路时要小心。',
  'celebrate|ˈselɪbreɪt|v.|庆祝|We celebrate the Spring Festival with family.|我们和家人一起庆祝春节。',
  'certain|ˈsɜːtn|adj.|确定的；某些|I am certain that he will come.|我确定他会来。',
  'challenge|ˈtʃælɪndʒ|n./v.|挑战|Learning English is a real challenge.|学英语是个真正的挑战。',
  'chance|tʃɑːns|n.|机会|Give me one more chance, please.|请再给我一次机会。',
  'choose|tʃuːz|v.|选择|You may choose any book you like.|你可以选任何你喜欢的书。',
  'clever|ˈklevə|adj.|聪明的|That is a clever way to save water.|那是个节水的聪明办法。',
  'climb|klaɪm|v.|爬，攀登|We climbed the hill last weekend.|上周末我们爬了那座小山。',
  'collect|kəˈlekt|v.|收集|My brother collects old stamps.|我弟弟收集旧邮票。',
  'comfortable|ˈkʌmftəbl|adj.|舒适的|This chair is very comfortable.|这把椅子非常舒服。',
  'common|ˈkɒmən|adj.|常见的；共同的|Colds are common in winter.|感冒在冬天很常见。',
  'communicate|kəˈmjuːnɪkeɪt|v.|交流，沟通|We communicate with each other by email.|我们通过邮件交流。',
  'compare|kəmˈpeə|v.|比较|Compare the two pictures and find the difference.|比较两幅图并找出不同。',
  'complete|kəmˈpliːt|v./adj.|完成；完整的|Please complete the form in ten minutes.|请在十分钟内填完表格。',
  'computer|kəmˈpjuːtə|n.|电脑|I use a computer to do my homework.|我用电脑做作业。',
  'condition|kənˈdɪʃn|n.|条件；状况|The bike is still in good condition.|这辆自行车状况仍然良好。',
  'connect|kəˈnekt|v.|连接|This bridge connects the two villages.|这座桥连接两个村庄。',
  'consider|kənˈsɪdə|v.|考虑|Please consider my suggestion carefully.|请仔细考虑我的建议。',
  'continue|kənˈtɪnjuː|v.|继续|The rain continued all night.|雨下了一整夜。',
  'control|kənˈtrəʊl|v./n.|控制|You must learn to control your temper.|你必须学会控制脾气。',
  'correct|kəˈrekt|adj./v.|正确的；改正|Your answer is not correct.|你的答案不正确。',
  'courage|ˈkʌrɪdʒ|n.|勇气|It takes courage to speak in public.|当众发言需要勇气。',
  'create|kriˈeɪt|v.|创造|Music can create a happy mood.|音乐能营造快乐的心情。',
  'culture|ˈkʌltʃə|n.|文化|Food is an important part of culture.|饮食是文化的重要部分。',
  'curious|ˈkjʊəriəs|adj.|好奇的|Children are curious about the world.|孩子们对世界充满好奇。',
  'dangerous|ˈdeɪndʒərəs|adj.|危险的|Swimming in the river is dangerous.|在河里游泳很危险。',
  'decide|dɪˈsaɪd|v.|决定|We decided to go by bus.|我们决定坐公交去。',
  'describe|dɪˈskraɪb|v.|描述|Can you describe the man you saw?|你能描述一下你看见的那个人吗？',
  'develop|dɪˈveləp|v.|发展；养成|Try to develop a habit of reading.|试着养成阅读的习惯。',
  'difference|ˈdɪfrəns|n.|差别|What is the difference between them?|它们之间有什么区别？',
  'difficult|ˈdɪfɪkəlt|adj.|困难的|This maths problem is too difficult.|这道数学题太难了。',
  'direction|dəˈrekʃn|n.|方向|We walked in the wrong direction.|我们走错了方向。',
  'discover|dɪˈskʌvə|v.|发现|Scientists discovered a new planet.|科学家发现了一颗新行星。',
  'discuss|dɪˈskʌs|v.|讨论|Let us discuss the plan after class.|我们课后讨论这个计划吧。',
  'disease|dɪˈziːz|n.|疾病|Washing hands helps prevent disease.|洗手有助于预防疾病。',
  'distance|ˈdɪstəns|n.|距离|The distance to school is two kilometres.|到学校的距离是两公里。',
  'dream|driːm|n./v.|梦；梦想|My dream is to become a doctor.|我的梦想是成为医生。',
  'effort|ˈefət|n.|努力|Great effort brings great progress.|巨大的努力带来巨大的进步。',
  'electric|ɪˈlektrɪk|adj.|电动的|An electric car is quieter than a petrol one.|电动车比汽油车安静。',
  'encourage|ɪnˈkʌrɪdʒ|v.|鼓励|My teacher encouraged me to try again.|老师鼓励我再试一次。',
  'energy|ˈenədʒi|n.|能量；精力|Solar energy is clean and free.|太阳能既清洁又免费。',
  'enough|ɪˈnʌf|adj./adv.|足够的|We have enough time to finish it.|我们有足够时间完成它。',
  'environment|ɪnˈvaɪrənmənt|n.|环境|We must protect the environment.|我们必须保护环境。',
  'especially|ɪˈspeʃəli|adv.|尤其，特别|I like fruit, especially oranges.|我喜欢水果，尤其是橙子。',
  'event|ɪˈvent|n.|事件；活动|Sports Day is the biggest event of the term.|运动会是本学期最大的活动。',
  'exactly|ɪɡˈzæktli|adv.|确切地|Tell me exactly what happened.|确切地告诉我发生了什么。',
  'examination|ɪɡˌzæmɪˈneɪʃn|n.|考试；检查|The examination lasts two hours.|考试持续两小时。',
  'example|ɪɡˈzɑːmpl|n.|例子|Can you give me an example?|你能给我举个例子吗？',
  'excited|ɪkˈsaɪtɪd|adj.|兴奋的|The children were excited about the trip.|孩子们对这次旅行很兴奋。',
  'exercise|ˈeksəsaɪz|n./v.|锻炼；练习|Daily exercise keeps you healthy.|每天锻炼使你健康。',
  'expect|ɪkˈspekt|v.|期望，预料|We expect good weather tomorrow.|我们预计明天天气不错。',
  'experience|ɪkˈspɪəriəns|n.|经历，经验|Travelling gives you rich experience.|旅行给你丰富的经历。',
  'explain|ɪkˈspleɪn|v.|解释|Could you explain this word again?|你能再解释一下这个词吗？',
  'express|ɪkˈspres|v.|表达|Use simple words to express your idea.|用简单的词表达你的想法。',
  'famous|ˈfeɪməs|adj.|著名的|Xi an is famous for its history.|西安以历史闻名。',
  'favourite|ˈfeɪvərɪt|adj.|最喜爱的|Basketball is my favourite sport.|篮球是我最喜欢的运动。',
  'feeling|ˈfiːlɪŋ|n.|感觉，情感|I had a strange feeling last night.|昨晚我有种奇怪的感觉。',
  'festival|ˈfestɪvl|n.|节日|The Mid-Autumn Festival is in September.|中秋节在九月。',
  'finally|ˈfaɪnəli|adv.|最后，终于|Finally, we found the missing key.|最后我们找到了丢失的钥匙。',
  'forget|fəˈɡet|v.|忘记|Do not forget to bring your notebook.|别忘了带笔记本。',
  'forward|ˈfɔːwəd|adv.|向前|We look forward to your reply.|我们期待你的回复。',
  'freedom|ˈfriːdəm|n.|自由|Everyone enjoys the freedom to choose.|人人都享有选择的自由。',
  'friendly|ˈfrendli|adj.|友好的|Our new neighbour is very friendly.|我们的新邻居非常友好。',
  'future|ˈfjuːtʃə|n.|未来|In the future, robots may cook for us.|将来机器人也许会为我们做饭。',
  'gather|ˈɡæðə|v.|聚集，收集|People gathered in the square.|人们聚集在广场上。',
  'general|ˈdʒenrəl|adj.|总体的，普遍的|In general, the plan works well.|总的来说，这个计划运作良好。',
  'gentle|ˈdʒentl|adj.|温和的|Speak in a gentle voice to the baby.|对婴儿要用温柔的声音说话。',
  'grade|ɡreɪd|n.|年级；成绩|She got a good grade in science.|她的科学成绩很好。',
  'health|helθ|n.|健康|Sleep is important for health.|睡眠对健康很重要。',
  'helpful|ˈhelpfl|adj.|有帮助的|Your notes were really helpful.|你的笔记真的很有用。',
  'imagine|ɪˈmædʒɪn|v.|想象|Imagine you are on a desert island.|想象你在一座荒岛上。',
  'important|ɪmˈpɔːtnt|adj.|重要的|It is important to keep promises.|信守承诺很重要。',
  'improve|ɪmˈpruːv|v.|改进，提高|Reading aloud can improve your speaking.|朗读能提高你的口语。',
];
